spring:
  application:
    name: gateway

server:
  port: 8080

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 15

zuul:
  routes:
    book-service:
      path: /book-service/**
      sensitive-headers: Set-Cookie,Autorization
    rating-service:
      path: /rathing-service/**
      sensitive-headers: Set-Cookies,Autorization
    discovery:
      path: /discovery/**
      sensitive-headers: Set-Cookie, Autorization

histrix:
  command:
    book-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    rating-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    discovery:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

